spring.application.name=purl
spring.liquibase.change-log=classpath:db/db-changelog.xml
spring.liquibase.enabled=true
spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite

server.tomcat.threads.max=10
server.tomcat.threads.min-spare=2
server.tomcat.accept-count=10

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.query.plan_cache_max_size=64
spring.jpa.properties.hibernate.query.plan_parameter_metadata_max_size=16

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1